#!/bin/bash

buildauxe="$buildroot/auxel"
buildconf="$buildauxe/config"
buildpack="$buildauxe/packer"
buildlibs="$buildauxe/corest"
builddata="$buildauxe/datum"


## DISTVARS
test -e "$builddata/raptors.conf" && source "$builddata/raptors.conf"


## FUNCTION
test -e "$buildauxe/makes" && source "$buildauxe/makes"
test -e "$buildauxe/makos" && source "$buildauxe/makos"


## PACKAGES
pack_pacmir="$buildpack/pacmir"
pack_packfa="$buildpack/packfa"
pack_packco="$buildpack/packco"
pack_pacman="$buildpack/instal"


## microcode
pack_ucodes=$(grep "vendor_id" /proc/cpuinfo | head -n 1 | awk '{print $3}')

if [[ "$pack_ucodes" == "GenuineIntel" ]]; then
    echo "intel-ucode" > "$pack_pacman"
elif [[ "$pack_ucodes" == "AuthenticAMD" ]]; then
    echo "amd-ucode"   > "$pack_pacman"
fi


## graphical


## gathering
cat $pack_pacmir >> $pack_pacman